# Generated by Django 3.1 on 2020-08-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_name', models.TextField()),
                ('first_price', models.IntegerField()),
                ('yesterday_price', models.IntegerField()),
                ('close_price', models.IntegerField()),
                ('close_price_change_percent', models.FloatField()),
                ('final_price', models.IntegerField()),
                ('final_price_change_percent', models.FloatField()),
                ('eps', models.IntegerField()),
                ('highest_price', models.IntegerField()),
                ('lowest_price', models.IntegerField()),
                ('pe', models.FloatField()),
                ('trade_volume', models.BigIntegerField()),
                ('trade_value', models.BigIntegerField()),
                ('market_value', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('industry', models.TextField()),
                ('market', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
